In [6]:
import os
import json
from pathlib import Path
import pandas as pd

In [12]:
DATA_DIR = Path.cwd() / "data"

# Read all data files present in DATA_DIR (non-recursive), sorted for stable output
FILES = sorted(
    [p.name for p in DATA_DIR.iterdir() if p.is_file() and p.suffix.lower() in {".jsonl", ".json", ".csv"}]
)

if not FILES:
    raise FileNotFoundError(f"No supported data files found in: {DATA_DIR}")

In [15]:
def _load_jsonl(path: Path) -> pd.DataFrame:
    rows = []
    with path.open("r", encoding="utf-8") as f:
        for i, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError as e:
                raise ValueError(f"Invalid JSON on line {i} in {path.name}: {e}") from e
    return pd.DataFrame(rows)

def _load_json(path: Path) -> pd.DataFrame:
    with path.open("r", encoding="utf-8") as f:
        obj = json.load(f)
    if isinstance(obj, list):
        return pd.DataFrame(obj)
    if isinstance(obj, dict):
        return pd.json_normalize(obj)
    raise ValueError(f"Unsupported JSON structure in {path.name}: expected list or dict")

def _load_csv(path: Path) -> pd.DataFrame:
    return pd.read_csv(path)

def _load_file(path: Path) -> pd.DataFrame:
    suffix = path.suffix.lower()
    if suffix == ".jsonl":
        return _load_jsonl(path)
    if suffix == ".json":
        return _load_json(path)
    if suffix == ".csv":
        return _load_csv(path)
    raise ValueError(f"Unsupported file type: {path.name}")

def explore_file(filename: str) -> dict:
    path = DATA_DIR / filename
    if not path.exists():
        raise FileNotFoundError(f"File not found: {path}")

    df = _load_jsonl(path)

    info = {
        "file": filename,
        "path": str(path),
        "rows": int(df.shape[0]),
        "columns": int(df.shape[1]),
        "column_names": list(df.columns),
        "summary": _summarize_df(df),
        "head": df.head(5),
    }
    return info

def _safe_unique_count(s: pd.Series) -> int:
    """
    Count unique values even if the series contains unhashable types (list/dict).
    """
    try:
        return int(s.nunique(dropna=True))
    except TypeError:
        def _to_hashable(x):
            # Must check for list/dict FIRST — pd.isna() on a list returns an array,
            # which raises ValueError when used in a boolean context.
            if isinstance(x, (list, dict)):
                # Stable string representation for nested JSON structures
                return json.dumps(x, sort_keys=True, ensure_ascii=False)
            try:
                if pd.isna(x):
                    return None
            except (TypeError, ValueError):
                # Fallback: stringify anything else that can't be NA-checked
                return str(x)
            return x

        return int(s.map(_to_hashable).nunique(dropna=True))

def _summarize_df(df: pd.DataFrame) -> pd.DataFrame:
    missing = df.isna().sum()
    non_null = df.notna().sum()

    summary = pd.DataFrame({
        "dtype": df.dtypes.astype(str),
        "missing_values": missing,
        "missing_pct": (missing / len(df) * 100).round(2) if len(df) else 0.0,
        "non_null": non_null,
        "unique": [ _safe_unique_count(df[c]) for c in df.columns ],
    }, index=df.columns).sort_index()

    return summary

def check_columns_consistency(results: list[dict], file_suffix: str) -> None:
    group = [r for r in results if r["file"].endswith(file_suffix)]
    print(f"\nSchema check for *{file_suffix} files")

    if not group:
        print("  No matching files found.")
        return
    if len(group) == 1:
        print(f"  Only one matching file ({group[0]['file']}); nothing to compare.")
        return

    baseline_file = group[0]["file"]
    baseline_cols = list(group[0]["column_names"])
    baseline_set = set(baseline_cols)

    same_sets = True
    same_order = True

    for r in group[1:]:
        cols = list(r["column_names"])
        cols_set = set(cols)

        if cols_set != baseline_set:
            same_sets = False
            missing = sorted(baseline_set - cols_set)
            extra = sorted(cols_set - baseline_set)
            print(f"  MISMATCH: {r['file']} vs {baseline_file}")
            print(f"    Missing columns: {missing if missing else 'None'}")
            print(f"    Extra columns:   {extra if extra else 'None'}")
        elif cols != baseline_cols:
            same_order = False
            print(f"  ORDER DIFFERENCE: {r['file']} has same columns but different order.")

    if same_sets and same_order:
        print(f"  OK: all {len(group)} files have identical columns and order.")
    elif same_sets:
        print(f"  OK (set): all {len(group)} files have the same columns, but order differs.")
    else:
        print(f"  FAIL: not all {len(group)} files share the same column set.")

In [16]:
results = []
for fn in FILES:
    res = explore_file(fn)
    results.append(res)

# Pretty print results per file
for res in results:
    print("=" * 100)
    print(f"FILE: {res['file']}")
    print(f"PATH: {res['path']}")
    print(f"SHAPE: {res['rows']} rows x {res['columns']} columns")
    print(f"COLUMNS: {res['column_names']}")
    print("-" * 100)
    display(res["summary"])
    print("-" * 100)
    display(res["head"])

check_columns_consistency(results, "_data.jsonl")
check_columns_consistency(results, "_label.jsonl")

====================================================================================================
FILE: en_test_data.jsonl
PATH: C:\Users\Jekaterina.Sergejeva\OneDrive - Euromonitor International\Desktop\SHROOM-CAP-EN-LT\data\en_test_data.jsonl
SHAPE: 240 rows x 15 columns
COLUMNS: ['index', 'title', 'abstract', 'doi', 'url', 'extracted', 'datafile', 'authors', 'question', 'model_id', 'model_config', 'prompt', 'output_text', 'output_tokens', 'output_logits']
----------------------------------------------------------------------------------------------------

                dtype  missing_values  missing_pct  non_null  unique
abstract          str               0          0.0       240      30
authors        object               0          0.0       240      30
datafile          str               0          0.0       240       2
doi               str               0          0.0       240      30
extracted        bool               0          0.0       240       2
index             str               0          0.0       240     240
model_config      str               0          0.0       240       3
model_id          str               0          0.0       240       2
output_logits  object               0          0.0       240     227
output_text       str               0          0.0       240     224
output_tokens  object               0          0.0       240     225
prompt            str               0          0.0       240      60
question          str               0          0.0       240      30
title             str               0          0.0       240      30
url               str               0          0.0       240      30

----------------------------------------------------------------------------------------------------

,index,title,abstract,doi,url,extracted,datafile,authors,question,model_id,model_config,prompt,output_text,output_tokens,output_logits
0,en-tst-0,Pretraining Data Detection for Large Language ...,As the scale of training corpora for large lan...,10.18653/v1/2024.emnlp-main.300,https://github.com/zhang-wei-chao/DC-PDD,False,2024.emnlp.xml,"[{'first': 'Weichao', 'last': 'Zhang'}, {'firs...",What is the name of the Chinese-language bench...,lmsys/vicuna-7b-v1.5,k50_p0.95_t0.2,"In the article titled ""Pretraining Data Detect...",2. What is the name of the benchmark that is c...,"[<0x0A>, 2, ., ▁What, ▁is, ▁the, ▁name, ▁of, ▁...","[18.2342338562, 12.4345569611, 19.5700969696, ..."
1,en-tst-1,Formality is Favored: Unraveling the Learning ...,Having been trained on massive pretraining dat...,10.18653/v1/2024.emnlp-main.304,https://aclanthology.org/2024.emnlp-main.304.pdf,True,2024.emnlp.xml,"[{'first': 'Jiahuan', 'last': 'Li'}, {'first':...",What five characteristics are associated as in...,lmsys/vicuna-7b-v1.5,k50_p0.95_t0.2,"In the article titled ""Formality is Favored: U...",(1) CORA (2) Citeseer (3) Pubmed (4) Web of Sc...,"[<0x0A>, ▁(, 1, ), ▁C, OR, A, ▁(, 2, ), ▁Cit, ...","[18.3630599976, 13.0511350632, 13.3475074768, ..."
2,en-tst-5,"An image speaks a thousand words, but can ever...","Given the rise of multimedia content, human tr...",10.18653/v1/2024.emnlp-main.573,https://aclanthology.org/2024.emnlp-main.573.pdf,True,2024.emnlp.xml,"[{'first': 'Simran', 'last': 'Khanuja'}, {'fir...",Name the three pipelines for image transcreation.,lmsys/vicuna-7b-v1.5,k50_p0.95_t0.2,"In the article titled ""An image speaks a thous...",The article discusses the challenges of image ...,"[<0x0A>, <0x0A>, The, ▁article, ▁discuss, es, ...","[21.6078338623, 20.6981983185, 15.7419433594, ..."
3,en-tst-6,Fishing for Magikarp: Automatically Detecting ...,The disconnect between tokenizer creation and ...,10.18653/v1/2024.emnlp-main.649,https://aclanthology.org/2024.emnlp-main.649.pdf,True,2024.emnlp.xml,"[{'first': 'Sander', 'last': 'Land'}, {'first'...",What are UNREACHABLE TOKENS?,lmsys/vicuna-7b-v1.5,k50_p0.95_t0.2,"In the article titled ""Fishing for Magikarp: A...",(https://arxiv.org/abs/2105.14599),"[<0x0A>, ▁(, https, ://, ar, xiv, ., org, /, a...","[21.6736106873, 12.5693969727, 12.4558324814, ..."
4,en-tst-7,SUPER: Evaluating Agents on Setting Up and Exe...,Given that Large Language Models (LLMs) have m...,10.18653/v1/2024.emnlp-main.702,https://aclanthology.org/2024.emnlp-main.702.pdf,True,2024.emnlp.xml,"[{'first': 'Ben', 'last': 'Bogin'}, {'first': ...",What is the full form of SUPER benchmark?,lmsys/vicuna-7b-v1.5,k50_p0.95_t0.2,"In the article titled ""SUPER: Evaluating Agent...",I couldn't find it in the article.,"[<0x0A>, I, ▁couldn, ', t, ▁find, ▁it, ▁in, ▁t...","[23.3552093506, 12.4487380981, 15.2110424042, ..."

====================================================================================================
FILE: en_train2_data.jsonl
PATH: C:\Users\Jekaterina.Sergejeva\OneDrive - Euromonitor International\Desktop\SHROOM-CAP-EN-LT\data\en_train2_data.jsonl
SHAPE: 84 rows x 15 columns
COLUMNS: ['index', 'title', 'abstract', 'doi', 'url', 'extracted', 'datafile', 'authors', 'question', 'model_id', 'model_config', 'prompt', 'output_text', 'output_tokens', 'output_logits']
----------------------------------------------------------------------------------------------------

                dtype  missing_values  missing_pct  non_null  unique
abstract          str              28        33.33        56       7
authors        object               0         0.00        84      14
datafile          str               0         0.00        84       7
doi               str               8         9.52        76      12
extracted        bool               0         0.00        84       2
index             str               0         0.00        84      84
model_config      str               0         0.00        84       3
model_id          str               0         0.00        84       2
output_logits  object               0         0.00        84      78
output_text       str               0         0.00        84      78
output_tokens  object               0         0.00        84      78
prompt            str               0         0.00        84      21
question          str               0         0.00        84      14
title             str               0         0.00        84      14
url               str               0         0.00        84      14

----------------------------------------------------------------------------------------------------

,index,title,abstract,doi,url,extracted,datafile,authors,question,model_id,model_config,prompt,output_text,output_tokens,output_logits
0,en-train2-2,Words Worth a Thousand Pictures: Measuring and...,Diffusion models are the state of the art in t...,10.18653/v1/2024.emnlp-main.311,https://aclanthology.org/2024.emnlp-main.311.pdf,True,2024.emnlp.xml,"[{'first': 'Raphael', 'last': 'Tang'}, {'first...",Which three state-of-the-art models are target...,lmsys/vicuna-7b-v1.5,k50_p0.95_t0.2,"In the article titled ""Words Worth a Thousand ...",1. GPT-32. DALL-E 23. CLIPAnswer: 1. GPT-32. D...,"[<0x0A>, 1, ., ▁G, PT, -, 3, <0x0A>, 2, ., ▁D,...","[20.0040550232, 10.1074323654, 20.1280994415, ..."
1,en-train2-4,Towards Robust Speech Representation Learning ...,Self-supervised learning (SSL) has helped exte...,10.18653/v1/2024.emnlp-main.570,https://aclanthology.org/2024.emnlp-main.570.pdf,True,2024.emnlp.xml,"[{'first': 'William', 'last': 'Chen'}, {'first...",The final pre-training dataset spans how many ...,lmsys/vicuna-7b-v1.5,k50_p0.95_t0.2,"In the article titled ""Towards Robust Speech R...",2000 languages?,"[<0x0A>, 2, 0, 0, 0, ▁languages, ?, </s>]","[19.4333019257, 11.7700519562, 16.1875114441, ..."
2,en-train2-15,What the Harm? Quantifying the Tangible Impact...,Gender bias in machine translation (MT) is rec...,10.18653/v1/2024.emnlp-main.1002,https://aclanthology.org/2024.emnlp-main.1002.pdf,True,2024.emnlp.xml,"[{'first': 'Beatrice', 'last': 'Savoldi'}, {'f...",Which three language pairs does the work include?,lmsys/vicuna-7b-v1.5,k50_p0.95_t0.2,"In the article titled ""What the Harm? Quantify...",1. English-French2. English-German3. English-S...,"[<0x0A>, 1, ., ▁English, -, F, rench, <0x0A>, ...","[19.7073287964, 12.2365903854, 19.6838340759, ..."
3,en-train2-19,"Twists, Humps, and Pebbles: Multilingual Speec...",Current automatic speech recognition (ASR) mod...,10.18653/v1/2024.emnlp-main.1188,https://aclanthology.org/2024.emnlp-main.1188.pdf,True,2024.emnlp.xml,"[{'first': 'Giuseppe', 'last': 'Attanasio'}, {...",Which two metrics are used to evaluate transcr...,lmsys/vicuna-7b-v1.5,k50_p0.95_t0.2,"In the article titled ""Twists, Humps, and Pebb...",(1) Word error rate (WER) and (2) Word error r...,"[<0x0A>, ▁(, 1, ), ▁Word, ▁error, ▁rate, ▁(, W...","[20.3124809265, 12.7483787537, 12.7798118591, ..."
4,en-train2-23,Midge: Generating Image Descriptions From Comp...,NaN,NaN,https://aclanthology.org/E12-1076.pdf,True,E12.xml,"[{'first': 'Margaret', 'last': 'Mitchell'}, {'...",How many PASCAL images does the evaluation ima...,lmsys/vicuna-7b-v1.5,k50_p0.95_t0.2,"In the article titled ""Midge: Generating Image...","(Note: PASCAL stands for ""Pattern Analysis, St...","[<0x0A>, ▁(, Note, :, ▁P, ASC, AL, ▁stands, ▁f...","[19.4977779388, 13.189447403, 11.7162952423, 2..."

====================================================================================================
FILE: en_train2_label.jsonl
PATH: C:\Users\Jekaterina.Sergejeva\OneDrive - Euromonitor International\Desktop\SHROOM-CAP-EN-LT\data\en_train2_label.jsonl
SHAPE: 84 rows x 3 columns
COLUMNS: ['index', 'has_fluency_mistakes', 'has_factual_mistakes']
----------------------------------------------------------------------------------------------------

                     dtype  missing_values  missing_pct  non_null  unique
has_factual_mistakes   str               0          0.0        84       2
has_fluency_mistakes   str               0          0.0        84       2
index                  str               0          0.0        84      84

----------------------------------------------------------------------------------------------------

          index has_fluency_mistakes has_factual_mistakes
0   en-train2-2                    y                    y
1   en-train2-4                    n                    y
2  en-train2-15                    n                    y
3  en-train2-19                    y                    y
4  en-train2-23                    n                    y

====================================================================================================
FILE: en_train_data.jsonl
PATH: C:\Users\Jekaterina.Sergejeva\OneDrive - Euromonitor International\Desktop\SHROOM-CAP-EN-LT\data\en_train_data.jsonl
SHAPE: 24 rows x 15 columns
COLUMNS: ['index', 'title', 'abstract', 'doi', 'url', 'extracted', 'datafile', 'authors', 'question', 'model_id', 'model_config', 'prompt', 'output_text', 'output_tokens', 'output_logits']
----------------------------------------------------------------------------------------------------

                dtype  missing_values  missing_pct  non_null  unique
abstract          str               4        16.67        20      20
authors        object               0         0.00        24      24
datafile          str               0         0.00        24      14
doi               str               3        12.50        21      21
extracted        bool               0         0.00        24       2
index             str               0         0.00        24      24
model_config      str               0         0.00        24       1
model_id          str               0         0.00        24       1
output_logits  object               0         0.00        24      24
output_text       str               0         0.00        24      24
output_tokens  object               0         0.00        24      24
prompt            str               0         0.00        24      24
question          str               0         0.00        24      24
title             str               0         0.00        24      24
url               str               0         0.00        24      24

----------------------------------------------------------------------------------------------------

,index,title,abstract,doi,url,extracted,datafile,authors,question,model_id,model_config,prompt,output_text,output_tokens,output_logits
0,en-train-0,Extrinsic Evaluation of Machine Translation Me...,Automatic machine translation (MT) metrics are...,10.18653/v1/2023.acl-long.730,https://aclanthology.org/2023.acl-long.730.pdf,True,2023.acl.xml,"[{'first': 'Nikita', 'last': 'Moghe'}, {'first...",What do the authors use extractive QA for in t...,meta-llama/Meta-Llama-3-8B-Instruct,k50_p0.95_t0.2,"In the article titled ""Extrinsic Evaluation of...","According to the article ""Extrinsic Evaluation...","[According, Ġto, Ġthe, Ġarticle, Ġ"", Ex, trins...","[28.9543380737, 25.1273345947, 31.0050830841, ..."
1,en-train-1,COKE: A Cognitive Knowledge Graph for Machine ...,Theory of mind (ToM) refers to humans’ ability...,10.18653/v1/2024.acl-long.848,https://aclanthology.org/2024.acl-long.848.pdf,True,2024.acl.xml,"[{'first': 'Jincenzi', 'last': 'Wu'}, {'first'...",What are the two steps that the authors used f...,meta-llama/Meta-Llama-3-8B-Instruct,k50_p0.95_t0.2,"In the article titled ""COKE: A Cognitive Knowl...","I apologize, but I couldn't find any informati...","[I, Ġapologize, ,, Ġbut, ĠI, Ġcouldn, 't, Ġfin...","[26.1247177124, 23.2479915619, 31.8196659088, ..."
2,en-train-2,G-DIG: Towards Gradient-based DIverse and hiGh...,Large Language Models (LLMs) have demonstrated...,10.18653/v1/2024.acl-long.821,https://aclanthology.org/2024.acl-long.821.pdf,True,2024.acl.xml,"[{'first': 'Xingyuan', 'last': 'Pan'}, {'first...",How do the authors make the high-quality data ...,meta-llama/Meta-Llama-3-8B-Instruct,k50_p0.95_t0.2,"In the article titled ""G-DIG: Towards Gradient...",A very specific and technical question!In the ...,"[A, Ġvery, Ġspecific, Ġand, Ġtechnical, Ġquest...","[26.1165943146, 22.3236026764, 27.7754478455, ..."
3,en-train-3,"Climbing towards NLU: On Meaning, Form, and Un...",The success of the large neural language model...,10.18653/v1/2020.acl-main.463,https://aclanthology.org/2020.acl-main.463.pdf,True,2020.acl.xml,"[{'first': 'Emily M.', 'last': 'Bender'}, {'fi...","What do the authors mean when they say that ""a...",meta-llama/Meta-Llama-3-8B-Instruct,k50_p0.95_t0.2,"In the article titled ""Climbing towards NLU: O...","In the article ""Climbing towards NLU: On Meani...","[In, Ġthe, Ġarticle, Ġ"", C, lim, bing, Ġtoward...","[28.6671924591, 27.6783638, 26.4121170044, 30...."
4,en-train-4,A Balanced Data Approach for Evaluating Cross-...,We show that the choice of pretraining languag...,10.18653/v1/2022.naacl-main.361,https://aclanthology.org/2022.naacl-main.361.pdf,True,2022.naacl.xml,"[{'first': 'Dan', 'last': 'Malkin'}, {'first':...","What are the ""blood"" and ""Blood bank"" metaphor...",meta-llama/Meta-Llama-3-8B-Instruct,k50_p0.95_t0.2,"In the article titled ""A Balanced Data Approac...","In the article ""A Balanced Data Approach for E...","[In, Ġthe, Ġarticle, Ġ"", A, ĠBalanced, ĠData, ...","[26.9458045959, 31.6627483368, 27.6575069427, ..."

====================================================================================================
FILE: en_train_label.jsonl
PATH: C:\Users\Jekaterina.Sergejeva\OneDrive - Euromonitor International\Desktop\SHROOM-CAP-EN-LT\data\en_train_label.jsonl
SHAPE: 24 rows x 3 columns
COLUMNS: ['index', 'has_fluency_mistakes', 'has_factual_mistakes']
----------------------------------------------------------------------------------------------------

                     dtype  missing_values  missing_pct  non_null  unique
has_factual_mistakes   str               0          0.0        24       2
has_fluency_mistakes   str               0          0.0        24       1
index                  str               0          0.0        24      24

----------------------------------------------------------------------------------------------------

        index has_fluency_mistakes has_factual_mistakes
0  en-train-0                    n                    y
1  en-train-1                    n                    n
2  en-train-2                    n                    y
3  en-train-3                    n                    y
4  en-train-4                    n                    y

====================================================================================================
FILE: en_valid_data.jsonl
PATH: C:\Users\Jekaterina.Sergejeva\OneDrive - Euromonitor International\Desktop\SHROOM-CAP-EN-LT\data\en_valid_data.jsonl
SHAPE: 240 rows x 15 columns
COLUMNS: ['index', 'title', 'abstract', 'doi', 'url', 'extracted', 'datafile', 'authors', 'question', 'model_id', 'model_config', 'prompt', 'output_text', 'output_tokens', 'output_logits']
----------------------------------------------------------------------------------------------------

                dtype  missing_values  missing_pct  non_null  unique
abstract          str              21         8.75       219      27
authors        object               0         0.00       240      30
datafile          str               0         0.00       240       6
doi               str              24        10.00       216      27
extracted        bool               0         0.00       240       2
index             str               0         0.00       240     240
model_config      str               0         0.00       240       3
model_id          str               0         0.00       240       2
output_logits  object               0         0.00       240     229
output_text       str               0         0.00       240     228
output_tokens  object               0         0.00       240     228
prompt            str               0         0.00       240      57
question          str               0         0.00       240      30
title             str               0         0.00       240      30
url               str               0         0.00       240      30

----------------------------------------------------------------------------------------------------

,index,title,abstract,doi,url,extracted,datafile,authors,question,model_id,model_config,prompt,output_text,output_tokens,output_logits
0,en-val-0,Aya Model: An Instruction Finetuned Open-Acces...,Recent breakthroughs in large language models ...,10.18653/v1/2024.acl-long.845,https://aclanthology.org/2024.acl-long.845.pdf,True,2024.acl.xml,"[{'first': 'Ahmet', 'last': 'Üstün'}, {'first'...",What is the quote said by Ludwig Wittgenstein ...,meta-llama/Meta-Llama-3-8B-Instruct,k50_p0.95_t0.2,"In the article titled ""Aya Model: An Instructi...","According to the article ""Aya Model: An Instru...","[According, Ġto, Ġthe, Ġarticle, Ġ"", A, ya, ĠM...","[24.9636917114, 27.9168376923, 24.58436203, 23..."
1,en-val-3,MMToM-QA: Multimodal Theory of Mind Question A...,"Theory of Mind (ToM), the ability to understan...",10.18653/v1/2024.acl-long.851,https://aclanthology.org/2024.acl-long.851.pdf,True,2024.acl.xml,"[{'first': 'Chuanyang', 'last': 'Jin'}, {'firs...",MMToM-QA Benchmark consists of how many videos...,meta-llama/Meta-Llama-3-8B-Instruct,k50_p0.95_t0.2,"In the article titled ""MMToM-QA: Multimodal Th...","According to the article ""MMToM-QA: Multimodal...","[According, Ġto, Ġthe, Ġarticle, Ġ"", MM, To, M...","[28.6483974457, 32.2784843445, 29.7794380188, ..."
2,en-val-4,MAP’s not dead yet: Uncovering true language m...,It has been widely observed that exact or appr...,10.18653/v1/2024.acl-long.855,https://aclanthology.org/2024.acl-long.855.pdf,True,2024.acl.xml,"[{'first': 'Davis', 'last': 'Yoshida'}, {'firs...",What is the name of the search method mentione...,meta-llama/Meta-Llama-3-8B-Instruct,k50_p0.95_t0.2,"In the article titled ""MAP’s not dead yet: Unc...","According to the article ""MAP’s not dead yet: ...","[According, Ġto, Ġthe, Ġarticle, Ġ"", MAP, âĢĻs...","[29.010225296, 32.7618408203, 31.4420127869, 2..."
3,en-val-5,NounAtlas: Filling the Gap in Nominal Semantic...,Despite significant advances in Semantic Role ...,10.18653/v1/2024.acl-long.857,https://aclanthology.org/2024.acl-long.857.pdf,True,2024.acl.xml,"[{'first': 'Roberto', 'last': 'Navigli'}, {'fi...",What is the name of the inventory of predicate...,meta-llama/Meta-Llama-3-8B-Instruct,k50_p0.95_t0.2,"In the article titled ""NounAtlas: Filling the ...","According to the article ""NounAtlas: Filling t...","[According, Ġto, Ġthe, Ġarticle, Ġ"", N, oun, A...","[29.7511863708, 32.4851608276, 31.1871871948, ..."
4,en-val-6,The Earth is Flat because...: Investigating LL...,Large language models (LLMs) encapsulate vast ...,10.18653/v1/2024.acl-long.858,https://aclanthology.org/2024.acl-long.858.pdf,True,2024.acl.xml,"[{'first': 'Rongwu', 'last': 'Xu'}, {'first': ...",Name the 3 QA datasets from which 1500 questio...,meta-llama/Meta-Llama-3-8B-Instruct,k50_p0.95_t0.2,"In the article titled ""The Earth is Flat becau...","According to the article ""The Earth is Flat be...","[According, Ġto, Ġthe, Ġarticle, Ġ"", The, ĠEar...","[29.0698108673, 29.0795650482, 32.0712051392, ..."

====================================================================================================
FILE: en_valid_label.jsonl
PATH: C:\Users\Jekaterina.Sergejeva\OneDrive - Euromonitor International\Desktop\SHROOM-CAP-EN-LT\data\en_valid_label.jsonl
SHAPE: 240 rows x 3 columns
COLUMNS: ['index', 'has_fluency_mistakes', 'has_factual_mistakes']
----------------------------------------------------------------------------------------------------

                     dtype  missing_values  missing_pct  non_null  unique
has_factual_mistakes   str               0          0.0       240       2
has_fluency_mistakes   str               0          0.0       240       2
index                  str               0          0.0       240     240

----------------------------------------------------------------------------------------------------

      index has_fluency_mistakes has_factual_mistakes
0  en-val-0                    n                    n
1  en-val-3                    n                    y
2  en-val-4                    n                    y
3  en-val-5                    n                    y
4  en-val-6                    n                    y

Schema check for *_data.jsonl files
  OK: all 4 files have identical columns and order.

Schema check for *_label.jsonl files
  OK: all 3 files have identical columns and order.

In [18]:
check_columns_consistency(def build_group_schema(results: list[dict], file_suffix: str) -> dict[str, str]:
    group = [r for r in results if r["file"].endswith(file_suffix)]
    if not group:
        return {}

    # Build schema from first matching file: {column_name: dtype}
    first = group[0]
    first_summary = first["summary"]
    schema = {
        col: str(first_summary.loc[col, "dtype"])
        for col in first["column_names"]
    }

    # Optional strictness: ensure all files in the group have the same column->dtype mapping
    for r in group[1:]:
        s = r["summary"]
        current = {col: str(s.loc[col, "dtype"]) for col in r["column_names"]}
        if current != schema:
            raise ValueError(
                f"Schema mismatch in {r['file']} for suffix {file_suffix}. "
                "Column names/types are not identical across files."
            )

    return schema


def save_group_schema(results: list[dict], file_suffix: str, output_filename: str) -> Path:
    schema = build_group_schema(results, file_suffix)
    output_path = DATA_DIR / output_filename

    with output_path.open("w", encoding="utf-8") as f:
        json.dump(schema, f, indent=2, ensure_ascii=False)

    print(f"Schema saved: {output_path}")
    return output_pathresults, "_data.jsonl")
check_columns_consistency(results, "_label.jsonl")

save_group_schema(results, "_data.jsonl", "schema_data.json")
save_group_schema(results, "_label.jsonl", "schema_label.json")

Schema check for *_data.jsonl files
  OK: all 4 files have identical columns and order.

Schema check for *_label.jsonl files
  OK: all 3 files have identical columns and order.
Schema saved: C:\Users\Jekaterina.Sergejeva\OneDrive - Euromonitor International\Desktop\SHROOM-CAP-EN-LT\data\schema_data.json
Schema saved: C:\Users\Jekaterina.Sergejeva\OneDrive - Euromonitor International\Desktop\SHROOM-CAP-EN-LT\data\schema_label.json

WindowsPath('C:/Users/Jekaterina.Sergejeva/OneDrive - Euromonitor International/Desktop/SHROOM-CAP-EN-LT/data/schema_label.json')

In [19]:
def build_group_schema(results: list[dict], file_suffix: str) -> dict[str, str]:
    group = [r for r in results if r["file"].endswith(file_suffix)]
    if not group:
        return {}

    # Build schema from first matching file: {column_name: dtype}
    first = group[0]
    first_summary = first["summary"]
    schema = {
        col: str(first_summary.loc[col, "dtype"])
        for col in first["column_names"]
    }

    # Optional strictness: ensure all files in the group have the same column->dtype mapping
    for r in group[1:]:
        s = r["summary"]
        current = {col: str(s.loc[col, "dtype"]) for col in r["column_names"]}
        if current != schema:
            raise ValueError(
                f"Schema mismatch in {r['file']} for suffix {file_suffix}. "
                "Column names/types are not identical across files."
            )

    return schema


def save_group_schema(results: list[dict], file_suffix: str, output_filename: str) -> Path:
    schema = build_group_schema(results, file_suffix)
    output_path = DATA_DIR / output_filename

    with output_path.open("w", encoding="utf-8") as f:
        json.dump(schema, f, indent=2, ensure_ascii=False)

    print(f"Schema saved: {output_path}")
    return output_path

In [20]:
save_group_schema(results, "_data.jsonl", "schema_data.json")
save_group_schema(results, "_label.jsonl", "schema_label.json")

Schema saved: C:\Users\Jekaterina.Sergejeva\OneDrive - Euromonitor International\Desktop\SHROOM-CAP-EN-LT\data\schema_data.json
Schema saved: C:\Users\Jekaterina.Sergejeva\OneDrive - Euromonitor International\Desktop\SHROOM-CAP-EN-LT\data\schema_label.json

WindowsPath('C:/Users/Jekaterina.Sergejeva/OneDrive - Euromonitor International/Desktop/SHROOM-CAP-EN-LT/data/schema_label.json')